version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    # mysql-data という名前付きボリュームを作成して、MySQLコンテナ内の /var/lib/mysql（データ保存先）と接続
    volumes:
      - mysql_data:/var/lib/mysql
    # MySQLがちゃんと起動して使える状態かをチェックする設定
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
  backend:
    build:
      # Dockerイメージのビルドに使うコンテキスト（＝ファイルの起点）が .（現在のディレクトリ）
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    # MySQLが healthcheck で「healthy（正常）」と判定されるまで起動を待つ
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todo
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  mysql_data: