// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sawada-naoya/todo/backend/internal/handler"
	"github.com/sawada-naoya/todo/backend/internal/infrastructure"
	"github.com/sawada-naoya/todo/backend/internal/repository"
	"github.com/sawada-naoya/todo/backend/internal/usecase"
)

// Injectors from wire.go:

// InitializeHandlerは依存関係を自動構築してTaskHandlerを返すためのエントリーポイント関数
// wire.Build() に渡されたProviderSetを元に、構成を自動生成する
func InitializeHandler() *handler.TaskHandler {
	db := infrastructure.MustConnectMySQL()
	taskRepository := repository.NewTaskRepository(db)
	taskUsecase := usecase.NewTaskUsecase(taskRepository)
	taskHandler := handler.NewTaskHandler(taskUsecase)
	return taskHandler
}
